// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ApiharborKeyUsageSchema = z.object({
  id: z.string().uuid(),
  apiKeyId: z.string().uuid(),
  usageDate: z.coerce.date(),
  requests: z.number().default(0),
  tokens: z.number().nullable().optional(),
  costCents: z.number().default(0),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TApiharborKeyUsage = z.infer<typeof ApiharborKeyUsageSchema>;
export type TApiharborKeyUsageInsert = Omit<z.input<typeof ApiharborKeyUsageSchema>, TImmutableDBKeys>;
export type TApiharborKeyUsageUpdate = Partial<Omit<z.input<typeof ApiharborKeyUsageSchema>, TImmutableDBKeys>>;
