// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ApiharborKeyHealthChecksSchema = z.object({
  id: z.string().uuid(),
  apiKeyId: z.string().uuid(),
  status: z.string(),
  httpStatus: z.number().nullable().optional(),
  latencyMs: z.number().nullable().optional(),
  message: z.string().nullable().optional(),
  checkedAt: z.date()
});

export type TApiharborKeyHealthChecks = z.infer<typeof ApiharborKeyHealthChecksSchema>;
export type TApiharborKeyHealthChecksInsert = Omit<z.input<typeof ApiharborKeyHealthChecksSchema>, TImmutableDBKeys>;
export type TApiharborKeyHealthChecksUpdate = Partial<
  Omit<z.input<typeof ApiharborKeyHealthChecksSchema>, TImmutableDBKeys>
>;
