// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const ApiharborKeysSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  name: z.string(),
  provider: z.string(),
  description: z.string().nullable().optional(),
  encryptedApiKey: zodBuffer,
  healthStatus: z.string().default("unknown"),
  lastCheckedAt: z.date().nullable().optional(),
  lastLatencyMs: z.number().nullable().optional(),
  lastHttpStatus: z.number().nullable().optional(),
  lastMessage: z.string().nullable().optional(),
  lastUsedAt: z.date().nullable().optional(),
  quotaLimit: z.number().nullable().optional(),
  quotaRemaining: z.number().nullable().optional(),
  validationConfig: z.unknown().nullable().optional(),
  monitoringEnabled: z.boolean().default(true),
  monthlyBudgetCents: z.number().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TApiharborKeys = z.infer<typeof ApiharborKeysSchema>;
export type TApiharborKeysInsert = Omit<z.input<typeof ApiharborKeysSchema>, TImmutableDBKeys>;
export type TApiharborKeysUpdate = Partial<Omit<z.input<typeof ApiharborKeysSchema>, TImmutableDBKeys>>;
